[package]
name = "lnx-query"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = { workspace = true }
tantivy = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
poem-openapi = { workspace = true }
tracing = { workspace = true }
regex = { workspace = true }

lnx-common = { path = "../lnx-common" }
lnx-tantivy = { path = "../lnx-tantivy" }

[dev-dependencies]
rstest = { workspace = true }