[package]
name = "lnx-config"
version = "0.1.0"
edition = "2024"
description = "lnx config manages the binary service's settings."

[dependencies]
ahash = { workspace = true }
parking_lot = { workspace = true }
thiserror = { workspace = true }

[features]
# Enables thread local state.
thread-local = []