//
// Created by intellij-pest on 2025-04-04
// lql
// Author: chillfish8
//


// from
// | select
// | limit

WHITESPACE = _{ " " | "\t" | "\r" | "\n" }

char = {
    !("\"" | "\\") ~ ANY
    | "\\" ~ ("\"" | "\\" | "/" | "b" | "f" | "n" | "r" | "t")
    | "\\" ~ ("u" ~ ASCII_HEX_DIGIT{4})
}
inner_str = @{ char* }

string = { "\"" ~ inner_str ~ "\"" }
bytes = { "b" ~ string }
integer = { ("-")? ~ ASCII_DIGIT+ }
float = @{ integer ~ ("." ~ ASCII_DIGIT*)? ~ (^"e" ~ integer)? }
bool = { "true" | "false" }

literal = {
 string
 | bytes
 | integer
 | float
 | bool
}

ident = { ("_" | ASCII_ALPHA) ~ ( "_" | ASCII_ALPHANUMERIC )* }

kw_from = { "from" }
kw_select = { "select" }
kw_where = { "where" }
kw_limit = { "limit" }
kw_offset = { "offset" }
kw_group_by = { "group_by" }
kw_parallel = { "parallel" }

params = { literal* }

PIPE = _{ "|" }

query = {
    SOI
    ~ (        kw_from     ~ "(" ~ params ~ ")" )
    ~ ( PIPE ~ kw_select   ~ "(" ~ params ~ ")" )?
    ~ ( PIPE ~ kw_where    ~ "(" ~ params ~ ")" )?
    ~ ( PIPE ~ kw_limit    ~ "(" ~ integer  ~ ")" )?
    ~ ( PIPE ~ kw_offset   ~ "(" ~ integer  ~ ")" )?
    ~ ( PIPE ~ kw_group_by ~ "(" ~ params ~ ")" )?
    ~ ( PIPE ~ kw_parallel ~ "(" ~ integer? ~ ")" )?
    ~ EOI
}