[package]
name = "lnx-page-store"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = { workspace = true }
anyhow = { workspace = true }
ahash = { workspace = true }
crc32fast = { workspace = true }
glommio = { workspace = true }
rkyv = { workspace = true }
stable_deref_trait = { workspace = true }
tracing = { workspace = true }
bytes = { workspace = true }
memmap2 = { workspace = true }
parking_lot = { workspace = true }
smallvec = { workspace = true }
arc-swap = { workspace = true }
moka = { workspace = true }
humansize = { workspace = true }
tokio = { workspace = true }
crossbeam-channel = { workspace = true }

# Encryption at rest
chacha20poly1305 = { workspace = true }
sha2 = { workspace = true }
hmac = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }
crc32fast = { workspace = true }

[features]
# Enables huge page allocation tests within the cache.
test-huge-pages = []
# Enable miri tests (and disables the rest.)
test-miri = []