[package]
name = "lnx-fs"
version = "0.1.0"
edition = "2021"
description = "A virtualized file system for writing small blobs efficiently."


[dependencies]
async-trait = { workspace = true }
arc-swap = { workspace = true }
thiserror = { workspace = true }
glommio = { workspace = true }
sqlx = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_derive = { workspace = true }
slab = { workspace = true }
ulid = { workspace = true }
tracing = { workspace = true }
moka = { workspace = true }
flume = { workspace = true }
bon = { workspace = true }
tokio = { workspace = true }
futures-util = { workspace = true }
bytes = { workspace = true }
fnv = { workspace = true }
ahash = { workspace = true }
parking_lot = { workspace = true, features = ["arc_lock"] }
rmp-serde = { workspace = true }
tempfile = { workspace = true }
smallvec = { workspace = true }
memmap2 = { workspace = true }
bitvec = { workspace = true }
stable_deref_trait = { workspace = true }
crossbeam-queue = { workspace = true }

[dev-dependencies]
tracing-subscriber = { workspace = true }
tokio = { workspace = true }
fastrand = { workspace = true }
mockall = { workspace = true }
crc32fast = { workspace = true }

[features]
# Enables testing utilities like `VirtualFileSystem::create_for_test()`.
test-utils = []
