//! A page cache dynamically allocates virtual memory to allow partial or complete
//! caching of file contents while maintaining alignment and "contiguous" memory regions.
//!
//! This system handles incrementally locking ranges of the cache files, freeing unused pages
//! and managing the overall memory attempting to be used by the system.
//!
//! Internally this is done with a lot of unsafe and mmap calls.
//!
//! # WARNING!
//!
//! If you're reading this bit of the code, I am sorry, this is a _very_ complicated
//! system which does a ton of unsafe in order to minimise overhead since this is the
//! hottest bit of any code within the lnx project. Please take great care reading all
//! documentation & annotations around the code in this section because most types do
//! more than what they let on, particularly mutexes.
//!

mod block;
mod gc;
mod page;
mod prepared_read;
mod utils;

use std::hash::{BuildHasher, Hash, Hasher};
use std::io;
use std::ops::Range;
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::Arc;

use ahash::RandomState;
use dashmap::Entry;
use crate::config::PageSize;
pub use self::prepared_read::PreparedRead;
use self::utils::NoOpRandomState;
use crate::page_cache::block::{PageId, VirtualFileBlock};


#[derive(Debug, thiserror::Error)]
/// An error generated by the caching system.
pub enum CacheError {
    #[error("file not found")]
    /// The target file does not exist in the cache.
    FileNotFound,
    #[error("file already exists")]
    /// The target file already exists in the cache.
    FileAlreadyExists,
    #[error("range {range:?} is out of bounds, file size is {file_size}")]
    /// The file range attempting to be read is out of bounds.
    OutOfBounds {
        range: Range<usize>,
        file_size: usize,
    },
    #[error("{0}")]
    /// An IO error occurred. 
    /// 
    /// This is typically only relevant when creating the initial entry.
    IoError(#[from] io::Error),
}

/// A page cache holds files partially or full in memory using virtual memory
/// addressing.
///
// TODO: Eventually this will become a 2-stage cache.
// / This system is composed of a two stage cache using both an LFU and LRU eviction policy.
// /// This is used as a primary-secondary configuration where evictions from the primary (LFU) cache
// /// are inserted into the secondary (LRU) cache where they have another chance to be re-used
// /// while allowing the system to freely evict pages with low contention when it needs to
// /// create larger allocations for file reads.
// ///
// /// Internally the cache describes the memory regions used in the primary as the "cache memory"
// /// and the secondary as the "working memory". This is because the working memory is what is used
// /// for holding onto allocations that probably won't stay in the primary cache, or for doing
// /// large reads of multiple pages into contiguous blocks.
// ///
// /// ### Note about working memory behaviour
// ///
// /// If there is not enough working memory to fit an allocation, the system will return an
// /// "OutOfMemory" error, this is done to prevent accidental OOMs.
pub struct FilePageCache {
    /// The random state used to produce the hash values used in the Moka caches
    /// and file blocks table.
    random_state: RandomState,
    /// The configured page size of the cache.
    page_size: PageSize,
    /// The primary LFU cache (Cache memory.)
    primary: moka::sync::Cache<u64, PageId, NoOpRandomState>,
    /// The file blocks backing pages.
    file_blocks: Arc<dashmap::DashMap<u64, FileBlockState, NoOpRandomState>>,
}

impl FilePageCache {
    /// Create a new [FilePageCache] with the given cache size and page size.
    pub fn new(cache_size_bytes: usize, page_size: PageSize) -> Self {
        let num_pages_capacity = cache_size_bytes / page_size.num_bytes();
        
        let file_blocks = Arc::new(dashmap::DashMap::<u64, FileBlockState, _>::with_hasher(NoOpRandomState)); 
        
        let primary = moka::sync::Cache::builder()
            .max_capacity(num_pages_capacity as u64)
            .eviction_listener({
                let file_blocks = file_blocks.clone();
                
                move |k, page_id, _| {
                    let id = *k;
                    if let Some(block) = file_blocks.get(&id) {
                        let state = block.value();
                        state.mark_for_deletion(page_id);
                    }
                }
            })
            .build_with_hasher(NoOpRandomState);
        
        
        Self {
            page_size,
            random_state: RandomState::new(),
            primary,
            file_blocks,
        }        
    }
    
    /// Creates a [PreparedRead] which allows the system to load any pre-cached
    /// pages and work out what pages need to be loaded from disk.
    ///
    /// The prepared read will hold write guards to the pages it needs to write to
    /// which will prevent other reads from writing or accessing the page.
    ///
    /// NOTE:
    /// It is important to note that reading the file cache != no memory write, because this
    /// system has to somewhat seamlessly allow filling in blanks in the cache, the
    /// prepared reads may require writing certain pages (which you have probably gathered by now.)
    ///
    pub fn prepare_read<K: Hash>(
        &self,
        file: K,
        range: Range<usize>,
    ) -> Result<PreparedRead, CacheError> {
        let mut hasher = self.random_state.build_hasher();
        file.hash(&mut hasher);
        
        self.prepare_read_inner(
            hasher.finish(),
            hasher,
            range,
        )
    }

    #[inline(never)]
    fn prepare_read_inner(
        &self,
        file_id: u64,
        file_hash_state: ahash::AHasher,
        read_range: Range<usize>,
    ) -> Result<PreparedRead, CacheError> {
        let block_state = self.file_blocks
            .get(&file_id)
            .ok_or(CacheError::FileNotFound)?;

        if read_range.start > block_state.file_len && read_range.end > block_state.file_len {
            return Err(CacheError::OutOfBounds {
                range: read_range,
                file_size: block_state.file_len,
            })
        }
                
        let prepared = block_state.prepare_read(read_range);

        for page_id in prepared.page_range() {
            let mut hasher = file_hash_state.clone();
            page_id.hash(&mut hasher);
            let page_hash_id = hasher.finish();

            // Call `get` on the cache to register the page being accessed for the LFU.
            self.primary.get(&page_hash_id);
            // Update the primary cache.
            self.primary.insert(page_hash_id, page_id);
        }

        Ok(prepared)
    }
    
    /// Create a new empty file entry in the cache with a given size.
    /// 
    /// A file must already exist within the cache before it can be read/written to.
    pub fn create_cache_entry<K: Hash>(
        &self,
        file: K,
        file_size: usize,
    ) -> Result<(), CacheError> {
        let file_id = self.random_state.hash_one(file);        
        self.create_cache_entry_inner(file_id, file_size)
    }
    
    #[inline(never)]
    fn create_cache_entry_inner(
        &self,
        file_id: u64,
        file_size: usize,
    ) -> Result<(), CacheError> {
        if self.file_blocks.contains_key(&file_id) {
            return Err(CacheError::FileAlreadyExists);
        }
        
        let block = FileBlockState::allocate(file_id, file_size, self.page_size)?;
        
        match self.file_blocks.entry(file_id) {
            Entry::Occupied(_) => Err(CacheError::FileAlreadyExists),
            Entry::Vacant(entry) => {
                entry.insert(block);
                Ok(())
            },
        }
    }
    
    /// Remove an existing file entry from the cache.
    /// 
    /// This removes all pages currently cached and the backing of virtual memory.
    pub fn delete_cache_entry<K: Hash>(
        &self,
        file: K,
    ) {
        let mut hasher = self.random_state.build_hasher();
        file.hash(&mut hasher);

        self.delete_cache_entry_inner(
            hasher.finish(),
            hasher,
        )
    }

    #[inline(never)]
    fn delete_cache_entry_inner(
        &self,
        file_id: u64,
        file_hash_state: ahash::AHasher,
    ) {
        let Some((_, block)) = self.file_blocks.remove(&file_id) else { return; };
        
        // For each page in the block, invalidate its entry in the cache.
        for page_id in 0..block.block.num_pages() {
            let mut hasher = file_hash_state.clone();
            page_id.hash(&mut hasher);
            let page_hash_id = hasher.finish();
            self.primary.invalidate(&page_hash_id);
        }
    }
}

struct FileBlockState {
    file_id: u64,
    file_len: usize,
    generation_counter: AtomicU64,
    block: Arc<VirtualFileBlock>,
}

impl FileBlockState {
    fn allocate(
        file_id: u64,
        file_len: usize,
        page_size: PageSize
    ) -> io::Result<Self> {
        let block = VirtualFileBlock::allocate(file_len, page_size)?;
        
        Ok(Self {
            file_id,
            file_len,
            generation_counter: AtomicU64::default(),
            block: Arc::new(block),
        })        
    }
    
    fn prepare_read(&self, bytes_range: Range<usize>) -> PreparedRead {
        let generation_id = self.generation_counter.fetch_add(1, Ordering::Relaxed);

        let generation = TrackedGeneration {
            file_id: self.file_id,
            generation_id,
        };

        PreparedRead::from_block_and_generation(
            self.block.clone(),
            bytes_range,
            generation,
        )
    }
    
    fn mark_for_deletion(&self, page_id: PageId) {
        let generation_id = self.generation_counter.fetch_add(1, Ordering::Release);
        
        let block = self.block.clone();
        
        // WARNING
        // There is an implicit contract that this callback is unwind safe.
        // The way parking lot's mutexes works means this is unwind safe 
        // _for our use case_ since the lack of poisoning does not affect
        // the end result.
        let cleanup_callback = move || {
            let page_state = block.page_at(page_id);

            let flags = page_state.flags();

            // The page flag has been unset, we should not deallocate the page.
            if !flags.is_to_be_freed() {
                return true;
            }
            
            unsafe {
                // Try to acquire the lock, if we cannot, signal to the GC to reschedule.
                // 
                // # Safety:
                // We know the page state will live long enough and the guard
                // will be dropped before the block is deallocated as we
                // hold a strong reference to the page block.
                let Some(_guard) = page_state.try_acquire_write_guard() else { return false };
                
                // Now we have exclusive write access we need to check the flags again
                // to ensure there was no race happening when we first read the flags.
                let flags = page_state.flags();
                
                // Page no longer wants to be freed, abort.
                if !flags.is_to_be_freed() {
                    return true;                        
                }
                
                // # Safety
                // We have an exclusive write lock for the page and ensured the page 
                // is still marked as waiting to be freed, this means we can safely
                // call this operation without triggering use-after free or UB to readers.
                let did_free = block.free_page(page_id);                 
                
                if did_free {
                    // Set the page state as free now we know the page is given back to the OS.
                    page_state.set_free_unchecked();
                }
                
                // If the page did not get freed correctly, we have to re-schedule.
                did_free                
            }
        };
        
        gc::register_trigger(
            self.file_id,
            generation_id,
            cleanup_callback,
        );
    }
}

/// A generation with a unique monotonic ID.
///
/// When this object is dropped it triggers a GC notification.
pub struct TrackedGeneration {
    file_id: u64,
    generation_id: u64,
}

impl Drop for TrackedGeneration {
    fn drop(&mut self) {
        gc::mark_dead_generation(self.file_id, self.generation_id);
    }
}


#[cfg(test)]
mod tests {
    use super::*;
    
    #[test]
    fn test_small_cache_create() {
        let cache = FilePageCache::new(1 << 30, PageSize::Size8KB);
        
        cache
            .prepare_read(
                "test.txt",
                0..5,
            )
            .expect_err("Cache entry should not exist");
        
        cache
            .create_cache_entry(
                "test.txt",
                64 << 10,
            )
            .expect("Create entry");

        let mut read = cache
            .prepare_read(
                "test.txt",
                0..5,
            )
            .expect("Cache entry should exist");

        assert_eq!(read.generation_id(), 0);
        assert_eq!(read.page_range(), 0..1);
        
        let outstanding_write = read.next_outstanding_write();
        assert!(outstanding_write.is_some());
        
        let write_request = outstanding_write.unwrap();
        assert_eq!(write_request.bytes_range(), 0..8<<10);
    }
}