[package]
name = "lnx-rest"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }
poem = { workspace = true }
poem-openapi = { workspace = true }

# Internal crates
lnx-types = { workspace = true }