[package]
name = "lnx-tantivy"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = { workspace = true }
tantivy = { workspace = true }
tracing = { workspace = true }
parking_lot = { workspace = true }
bytes = { workspace = true }
stable_deref_trait = { workspace = true }
futures-lite = { workspace = true }
tokio = { workspace = true }
async-trait = { workspace = true }
serde_json = { workspace = true }
rayon = { workspace = true }
ahash = { workspace = true }

lnx-doc = { path = "../lnx-doc" }
lnx-fs = { path = "../lnx-fs" }

[dev-dependencies]
tokio = { workspace = true }
ulid = { workspace = true }
tempfile = { workspace = true }
tracing-subscriber = { workspace = true }
lnx-fs = { path = "../lnx-fs", features = ["test-utils"] }

[features]
tantivy-full = ["tantivy/mmap", "tantivy/lz4-compression", "tantivy/zstd-compression"]